name: Docker

env:
  DOCKER_IMAGE_VERSION: ${{ github.sha }}

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-pec-2:${{ env.DOCKER_IMAGE_VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-pec-2:latest .

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-pec-2:${{ env.DOCKER_IMAGE_VERSION }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-pec-2:latest
