name: Mobile Continuous Deployment

on:
    workflow_run:
        workflows: [CI]
        types:
            - completed
            
    workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Create .env file
        run: |
          echo "API_BASE_URL_ANDROID=${{ secrets.API_BASE_URL }}" > .env
          echo "API_BASE_URL_IOS=${{ secrets.API_BASE_URL }}" >> .env
          echo "API_BASE_URL_WEB=${{ secrets.API_BASE_URL }}" >> .env  
          echo "API_BASE_URL_DEFAULT=${{ secrets.API_BASE_URL }}" >> .env

      - name: List files in the current directory
        run: ls -la
      
      - name: Build APK with environment variables
        run: flutter build apk --release
      
      - name: Extract version from pubspec.yaml
        id: version
        run: |
          version=$(grep '^version:' pubspec.yaml | cut -d ' ' -f2 | cut -d '+' -f1)          
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          generate_release_notes: true
          files: |
            ./build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Done
        run: echo "Release v${{ steps.version.outputs.version }} déployée avec succès !"